class Autogenerated {
  int id;
  String anneeScolaire;
  int idUser;
  String nomParent;
  String email;
  String eleve;
  String nomEleve;
  String prenomEleve;
  String dateNaissance;
  String lieuNaissance;
  String classe;
  String matricule;
  String modePaiement;
  String montantInitial;
  String fraisOperateur;
  String fraisEliah;
  String montant;
  String telephone;
  String echeancier;
  String reference;
  String dateTransaction;
  int statut;
  String type;

  Autogenerated({
    required this.id,
    required this.anneeScolaire,
    required this.idUser,
    required this.nomParent,
    required this.email,
    required this.eleve,
    required this.nomEleve,
    required this.prenomEleve,
    required this.dateNaissance,
    required this.lieuNaissance,
    required this.classe,
    required this.matricule,
    required this.modePaiement,
    required this.montantInitial,
    required this.fraisOperateur,
    required this.fraisEliah,
    required this.montant,
    required this.telephone,
    required this.echeancier,
    required this.reference,
    required this.dateTransaction,
    required this.statut,
    required this.type,
  });

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      id: json['id'],
      anneeScolaire: json['annee_scolaire'],
      idUser: json['id_user'],
      nomParent: json['nom_parent'],
      email: json['email'],
      eleve: json['eleve'],
      nomEleve: json['nom_eleve'],
      prenomEleve: json['prenom_eleve'],
      dateNaissance: json['date_naissance'],
      lieuNaissance: json['lieu_naissance'],
      classe: json['classe'],
      matricule: json['matricule'],
      modePaiement: json['mode_paiement'],
      montantInitial: json['montant_initial'],
      fraisOperateur: json['frais_operateur'],
      fraisEliah: json['frais_eliah'],
      montant: json['montant'],
      telephone: json['telephone'],
      echeancier: json['echeancier'],
      reference: json['reference'],
      dateTransaction: json['date_transaction'],
      statut: json['statut'],
      type: json['type'],
    );
  }
}
